### ISSUE TITLE
음성 그룹 통화 시 자기 목소리가 들리는 버그 수정

### ISSUE THREAD

**Issue by KimTaeYoung0589** [My-Own-Weapon/wagu-front#106]
### 🐞 버그 설명

음성 그룹 통화 시 자기 목소리가 들림

### ✅ 예상 결과

나의 목소리를 제외한 나머지 사람들의 목소리가 들려야 함

### ❗ 실제 결과

나의 목소리를 포함한 나머지 참여자의 목소리가 모두 들림

### 💻 버그 시뮬레이션

시연 중 발생

**Comment by rlawogkr** [comment]
해결완료
